theme: jekyll-theme-minimal
title: Randomly Optimal Nonsense!
description: This is my blog about random stuff, it will be having contents on optimization and control in stochastic settings and its applications in different areas such as machine learning, signal processing and finance.
